-- Allow explicit queue_index values on insert so the application can control
-- dequeue order (interleaved TML/WBL calls) without relying on insertion order.
-- GENERATED BY DEFAULT still uses the sequence when no value is provided.
ALTER TABLE public.queue_items
  ALTER COLUMN queue_index
    SET GENERATED BY DEFAULT;
