name: torntools

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: torntools
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d torntools"]
      interval: 5s
      timeout: 5s
      retries: 5

  flyway:
    build:
      context: .docker/flyway
      dockerfile: Dockerfile
    command: -url=${DATABASE_URL} -user=${DATABASE_USER} -password=${DATABASE_PASSWORD} -schemas=public -outOfOrder=false -validateMigrationNaming=true repair migrate
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
