name: Deploy React App

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      clean:
        description: 'Clean publish branch before deploy'
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # If run manually, build the chosen ref; otherwise use the current one
          ref: ${{ github.ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci
      - run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/build
          publish_branch: gh-pages
          enable_jekyll: false
          force_orphan: true
          keep_files: ${{ inputs.clean == false }}
